### ISSUE TITLE
svg2pdc should be a separate tool

### ISSUE THREAD

**Issue by jehrhardt** [pebble-examples/cards-example#7]
svg2pdc seems to be a handy script and it could be moved to it's own Github repo. When it would be published to PyPI, it could easily be installed (maybe as part of the Pebble SDK 😉.

**Comment by tardypad** [comment]
+1

**Comment by C-D-Lewis** [comment]
The script was mistakenly published here, and remains here to serve as the de-facto public version (avoiding fragmentation). Perhaps in the future a more cohesive tool will be available.
